name: Build and Deploy Jekyll Site
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.x'
      - run: gem install bundler && bundle install
      - run: bundle exec jekyll build
      - uses: actions/upload-pages-artifact@v2
        with:
          path: _site
      - uses: actions/deploy-pages@v1

